#!/usr/bin/env sh

# Only run checks if files under ReactApp/ are staged.
if ! git diff --cached --name-only | grep -q "^ReactApp/"; then
  exit 0
fi

cd ReactApp
# Note: Use fast-fail chaining (&&) to avoid running tsc if lint-staged fails, and preventing masking of errors.
if [ -n "$MSYSTEM" ]; then
  npx.cmd lint-staged && npx.cmd tsc
else
  npx lint-staged && npx tsc
fi
