#!/usr/bin/env sh

# Only run checks if files under ReactApp/ are staged.
if ! git diff --cached --name-only | grep -q "^ReactApp/"; then
  exit 0
fi

cd ReactApp
if command -v npm.cmd > /dev/null 2>&1; then
  npx.cmd lint-staged
  npx.cmd tsc
else
  npx lint-staged
  npx tsc
fi
